### ISSUE TITLE
[Feat] Audio Feature Extracting

### ISSUE THREAD

**Issue by updaun** [boostcampaitech3/final-project-level3-cv-09#10]
### What?
- XDVioDet 모델 학습을 위한 데이터 준비
- 오디오 featrue 추출

### How?
- vggish를 활용한 오디오 피처 추출
- [XDVioDet Issue 내용 확인](https://github.com/Roc-Ng/XDVioDet/issues/15)
- [Tensorflow vggish](https://github.com/tensorflow/models/tree/master/research/audioset/vggish)
- [Pytorch vggish](https://github.com/harritaylor/torchvggish)

### Why?
- 한국 영화 데이터, 출혈 데이터 추가를 위한 피처 추출

### Todo
- [x] mp4 -> wav
- [x] tensorflow vggish 내용 확인
- [x] pytorch vggish 내용 확인
- [x] output embedding 표준화
- [x] output size 안 맞는 문제 해결

**Comment by ki3nd** [comment]
> 그래서 0.96을 0.66으로 줄여보았지만 여전히 250이 나왔다. STFT_HOP_LENGTH_SECONDS 를 0.01에서 0.007로 바꾸니까 360이 나왔다 하지만 int(round())때문에 다른 길이의 wav파일을 넣었을 때 같은 결과가 나올지 확신할 수는 없는 상황

You should first remove file .nyp with setting 0.96, and infer again. I tried with 0.66 but size is 363,128.

**Comment by updaun** [comment]
> 종이에 누락된 부분이 많아서 최대한 길이를 맞추려고 노력했습니다.
저희는 최대한 길이를 맞추려고 노력했지만 결국 포기하게 되었습니다.
최대한 길이를 조절하고 나머지 등 부분을 잘라 버렸습니다.

> Có rất nhiều thiếu sót trong bài báo, vì vậy chúng tôi đã cố gắng để khớp chiều dài càng nhiều càng tốt.
Tụi mình đã cố gắng để khớp chiều dài nhất có thể, nhưng cuối cùng tụi mình đã từ bỏ.
Mình đã điều chỉnh độ dài nhiều nhất có thể và cắt phần còn lại của mặt sau rồi vứt đi.

There were a lot of omissions in the paper, so we tried to match the length as much as possible.
We tried to match the length as much as possible, but we eventually gave up.
I adjusted the length as much as possible and cut the rest of the back and threw it away.
