### ISSUE TITLE
[Model] YOLOv5 Custom Trainning

### ISSUE THREAD

**Issue by yoonghee** [boostcampaitech3/final-project-level3-cv-09#36]
### What?
- violence localization (blood scene object detection)
- custom dataset 준비

### Why?
- violence localization + 모자이크(blur)

### Todo
- [x] pre-trained model, streamlit으로 http 송수신 해보기 (FastAPI)
- [x] 데이터 추가 수집 or 기존 400장에서 제외할 목록 정하기
- [x] 어노테이션 가이드 (어떤걸 라벨링하고, 크기는 어떻게할지) 작성하기
- [x] annotation tool research 및 Set-up
- [x] custom dataset annotation
- [x] custom trainning set-up
- [x] custom trainning
- [x] blood detection 영화 영상으로 테스트 해보기
- [x] movie data to image (2frame/1sec)
- [x] movie data annotation task (협업) (class 1개 -> 5개로 세분화)
- [x] trainning
- [x] 결과 테스트

### Reference
- dataset[400장] : https://github.com/shivansh10/Blood_Detection
- movie dataset : https://drive.google.com/drive/u/0/folders/1Be4Lz46APkLl679bAv2uiugs3vdiVZQL
- annotation tools : https://github.com/ManivannanMurugavel/Yolo-Annotation-Tool-New-
