### ISSUE TITLE
[Git] Pre-commit Black 적용하기

### ISSUE THREAD

**Issue by yoonghee** [boostcampaitech3/final-project-level3-cv-09#42]
## What?
Pre-commit 기능 중 하나인 자동 포맷팅 Black으로 적용해보기

## Why?
Python Code 자동 포맷팅으로 편리한 개발환경 구축
기타 툴도 하나하나 적용해볼 예정

## Todo
- [x] local에 테스트 해보기
- [x] 전체 팀원에게 적용하기
- [x] 다른 기능도 추가하기
