### ISSUE TITLE
[Feat] 대체 이미지 기능 추가

### ISSUE THREAD

**Issue by yoonghee** [boostcampaitech3/final-project-level3-cv-09#76]
### What?
- 폭력 구간에 대체 이미지 또는 gif를 넣는 기능 추가

### Todo
- [x] 모코코.gif 랜덤 좌표에 합성
- [x] mp4 -> opencv processing -> mp4 -> h264 코덱 변경 
- [x] 비디오 + 오디오 
- [x] 모자이크 할 부분에 불투명한 비눗방울 이미지 합성
- [ ] 큰 비눗방울 하나가 있는 png -> 풍성한 비눗방울 적용해보기
- [ ] 크기를 더 키워 더 가려질 수 있도록 필터링 영역 확장
- [ ] kinetics(violence_localization)에도 적용
- [ ] 피가 나오는 구간 이미지 전체를 GRAY SCALE로 변경 (논의 필요)
