### ISSUE TITLE
[Refactoring] FastAPI 개발환경 세팅 및 포팅

### ISSUE THREAD

**Issue by yoonghee** [boostcampaitech3/final-project-level3-cv-09#80]
### What?
- 백엔드를 분리하기 위해 FastAPI 초기 환경 세팅 및 이전 기능 그대로 사용할 수 있도록 포팅
- Dependency에 영향을 받지 않게 하기 위해 Dockerizing

### Todo
- [x] FastAPI 듀토리얼로 띄우기
- [x] Dockerizing
- [x] Streamlit 프론트와 API 송수신 테스트
- [x] 각 기능을 실행할 때마다 threshold set 하도록 구현
- [x] Violence Detection 기능 추가
- [x] Violence Filtering - YOLOv5
- [x] Violence Filtering - kinetics
- [x] Skip 기능 추가
- [x] Mute 기능 추가
- [x] 대체이미지 기능 추가
- [x] Reset 기능 추가

**Comment by km9mn** [comment]
[ ] 동영상을 웹에 업로드하면 백엔드에서 연산 후 스코어 그래프를 웹에 반환

**Comment by yoonghee** [comment]
> [ ] 동영상을 웹에 업로드하면 백엔드에서 연산 후 스코어 그래프를 웹에 반환

위에 1f3360a commit에 말씀하신대로 구현 완료하여 올렸습니다.
