### ISSUE TITLE
[Feat] Yolo Annotation Tool 기능 추가

### ISSUE THREAD

**Issue by jeongjae96** [boostcampaitech3/final-project-level3-cv-09#90]
### What?
- 기존에 사용하고 있는 Yolo Annotation Tool에 

### Todo
- [x] 선택된 bbox가 어느 box인지를 확인하기 위해 spacebar를 누를 시, 그 bbox의 색상을 변환하도록 한다.
- [ ] bbox 사이즈 조절 기능 추가
- [ ] 줌인/줌아웃 기능 추가
- [ ] 다른 이미지로 넘어가지 않을 시, bbox가 저장되지 않는 문제 해결하기
